spring:
  application:
    name: servicio-autenticacion

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.flywaydb: DEBUG
