spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      platform: postgres

server:
  port: 8080

adapter:
  restconsumer:
    timeout: 5000
    url: "http://backend:8080"

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
